version: "3.9"
services:
  passport_db:
    image: postgres
    container_name: passport_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=passport
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/passport_db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  app:
    image: passport
    container_name: passport
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://passport_db:5432/passport
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "127.0.0.1:80:8080"
    depends_on:
      - passport_db